package rockpaperscissors;
import java.util.Random;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alex
 */
public class rpsgui extends javax.swing.JFrame {
    Random random = new Random();
    int userscore = 0;
    int computerscore = 0;
    String[] rpsarray = {"rock","paper","scissors"};
    /**
     * Creates new form rpsgui
     */
    public rpsgui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        entertext = new javax.swing.JTextField();
        enterchoice = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        score = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextPane();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        entertext.setText("Enter choice");

        enterchoice.setText("OK");
        enterchoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterchoiceActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(score);
        score.setText("Scores will show up here");

        jScrollPane3.setViewportView(display);
        display.setText("Outcome will show up here");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(entertext, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(143, 143, 143)
                            .addComponent(enterchoice, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(entertext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(enterchoice)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterchoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterchoiceActionPerformed
        String userchoice = entertext.getText();
        userchoice = userchoice.toLowerCase();
        int randomnumber = random.nextInt(3);
        String computerchoice = rpsarray[randomnumber];
        if((userscore-computerscore)>4){
            randomnumber = random.nextInt(10);
            if (randomnumber == 7){
                computerchoice = "gun";
            }
        }
        if(userchoice.equals("rock") || userchoice.equals("paper") || userchoice.equals("scissors")){
            comparescores(userchoice, computerchoice);
        }else{
            display.setText("Please enter rock paper or scissors:");
            entertext.setText("");
        }
    }//GEN-LAST:event_enterchoiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rpsgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rpsgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rpsgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rpsgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rpsgui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane display;
    private javax.swing.JButton enterchoice;
    private javax.swing.JTextField entertext;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextPane score;
    // End of variables declaration//GEN-END:variables

    public void comparescores(String userchoice, String computerchoice){
        String outcome = "";
        if(userchoice.equals("rock")){
            if(computerchoice.equals("rock")){
                outcome = "draw";
            }else if(computerchoice.equals("paper")){
                outcome = "lose";
                computerscore++;
            }else if(computerchoice.equals("scissors")){
                outcome = "win";
                userscore++;
            }else if(computerchoice.equals("gun")){
                computerscore = 0;
                userscore = 0;
                outcome = "both have your scores reset to 0, don't hate the player, hate the game.\n̿̿ ̿̿ ̿̿ ̿'̿'\\̵͇̿̿\\з= ( ▀ ͜͞ʖ▀) =ε/̵͇̿̿/’̿’̿ ̿ ̿̿ ̿̿ ̿̿";
            }
        }else if(userchoice.equals("paper")){
            if(computerchoice.equals("paper")){
                outcome = "draw";
            }else if(computerchoice.equals("scissors")){
                outcome = "lose";
                computerscore++;
            }else if(computerchoice.equals("rock")){
                outcome = "win";
                userscore++;
            }else if(computerchoice.equals("gun")){
                computerscore = 0;
                userscore = 0;
                outcome = "both have your scores reset to 0, don't hate the player, hate the game.\n̿̿ ̿̿ ̿̿ ̿'̿'\\̵͇̿̿\\з= ( ▀ ͜͞ʖ▀) =ε/̵͇̿̿/’̿’̿ ̿ ̿̿ ̿̿ ̿̿";
            }
        }else if(userchoice.equals("scissors")){
            if(computerchoice.equals("scissors")){
                outcome = "draw";
            }else if(computerchoice.equals("rock")){
                outcome = "lose";
                computerscore++;
            }else if(computerchoice.equals("paper")){
                outcome = "win";
                userscore++;
            }else if(computerchoice.equals("gun")){
                computerscore = 0;
                userscore = 0;
                outcome = "both have your scores reset to 0, don't hate the player, hate the game.\n̿̿ ̿̿ ̿̿ ̿'̿'\\̵͇̿̿\\з= ( ▀ ͜͞ʖ▀) =ε/̵͇̿̿/’̿’̿ ̿ ̿̿ ̿̿ ̿̿";
            }
        }
        score.setText("User: "+userscore+" Computer: "+computerscore);
        display.setText("You picked "+userchoice+", computer picked "+computerchoice+", you "+outcome);
        entertext.setText("");
    }

}
